<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etiqueta [
<!ELEMENT lisya_personas (persona*)>
<!ELEMENT persona (nombre, fecha_nacimiento, sexo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
]>
<lista_personas>
    <persona>
    <nombre>Antonio Moreno</nombre>
    <fecha_nacimiento>27-11-2008</fecha_nacimiento>
    <sexo>Var√≥n</sexo>
    </persona>
</lista_personas>