=== Manubetis/Lengua-y-Marcas/TEMA 1: INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/Tarea 4/Ejercicio 5/DTD externa/discografica.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT discografica (disco*)>
<!ELEMENT disco (titulo, interpretes+, pista+)>
<!ELEMENT pista (nombreCancion, duracion)>
<!ELEMENT interpretes (nombre, apellido1, apellido2, funcion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT numeroPstas (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT funcion (#PCDATA)>
<!ELEMENT nombreCancion (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>

=== Manubetis/Lengua-y-Marcas/TEMA 1: INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/U1_T2_DTD/Ejercicio 5/DTD externa/discografica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE discografica SYSTEM "discografica.dtd">
<discografica>
    <disco>
        <titulo>Skrillex</titulo>
        <interpretes>
            <nombre>Arturo</nombre>
            <apellido1>Perez</apellido1>
            <apellido2>Kel</apellido2>
            <funcion>solista</funcion>
            </interpretes>
        <interpretes>
            <nombre>Felix</nombre>
            <apellido1>Jimenez</apellido1>
            <apellido2>Pin</apellido2>
            <funcion>guitarrista</funcion>
        </interpretes>
        <pista>
            <nombreCancion>LLelow</nombreCancion>
            <duracion>2:43</duracion>
        </pista>
    </disco>
</discografica>
