=== Manubetis/Lengua-y-Marcas/TEMA 1: INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/Prueba externa (DTD externa)/curso.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT curso (asignatura+)>
<!ELEMENT asignatura ((titulo|codigo), alumnos, profesor)>
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre, apellidos)>
<!ELEMENT profesor (nombre, apellidos)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>

=== Manubetis/Lengua-y-Marcas/TEMA 1: INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/Prueba externa (DTD externa)/curso.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curso SYSTEM "curso.dtd">
<curso>
    <asignatura>
        <titulo>Tecnologia</titulo>
        <alumnos>
            <alumno>Mamerto</alumno>
            <alumno>Lolita</alumno>
        </alumnos>
        <profesor>Eustaquio</profesor>
    </asignatura>
    <asignatura>
        <codigo>1907</codigo>
        <alumnos>
            <alumno>Angeli√±o</alumno>
            <alumno>Yengo</alumno>
        </alumnos>
        <profesor>Pou</profesor>
    </asignatura>
</curso>
